[project]
default_network = "pyevm"
dot_env = ".env"

# [networks.pyevm]
# [networks.eravm]

[networks.anvil]
chain_id = 31337
default_account_name = "anvil1"
prompt_live = false
save_to_db = false
unsafe_password_file = "~/.moccasin/unsafe-passwords/anvil1"
url = "http://127.0.0.1:8545"

[networks.sepolia]
chain_id = 11155111
default_account_name = "default"
explorer_type = "blockscout"
explorer_uri = "https://eth-sepolia.blockscout.com/"
save_to_db = false
url = "$SEPOLIA_RPC_URL"

[networks.sepolia-zksync]
chain_id = 300
default_account_name = "default"
explorer_type = "zksyncexplorer"
explorer_uri = "https://explorer.sepolia.era.zksync.dev"
is_zksync = true
save_to_db = true
url = "$SEPOLIA_ZKSYNC_RPC_URL"

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
