[project]
dependencies = [
  "titanoboa-zksync>=0.2.6",
  "vyper==0.4.0",
]
description = "Add your description here"
name = "moccasin_project"
readme = "README.md"
requires-python = ">=3.11"
version = "0.1.0"

[tool.uv]
prerelease = "allow"
